# Generated by Django 4.2.9 on 2024-01-15 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('pincode', models.AutoField(primary_key=True, serialize=False)),
                ('area_name', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_type',
            fields=[
                ('user_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_type_name', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.TextField(null=True)),
                ('email', models.TextField(null=True)),
                ('mobile', models.TextField(max_length=10, null=True)),
                ('display_picture', models.TextField(null=True)),
                ('address', models.TextField(null=True)),
                ('password', models.TextField(null=True)),
                ('security_question', models.TextField(null=True)),
                ('security_answer', models.TextField(null=True)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_side.city')),
                ('pincode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_side.area')),
                ('user_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_side.user_type')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='city_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_side.city'),
        ),
    ]
