# Generated by Django 4.2.9 on 2024-01-15 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city_id',
        ),
    ]
