# Generated by Django 4.2.9 on 2024-01-15 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0002_remove_user_city_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EAuction',
            fields=[
                ('e_auction_id', models.AutoField(primary_key=True, serialize=False)),
                ('e_auction_date_time', models.DateTimeField(null=True)),
                ('e_auction_duration', models.TimeField(null=True)),
                ('final_price', models.FloatField(null=True)),
                ('total_rounds', models.IntegerField(null=True)),
                ('quantity', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField(null=True)),
                ('order_status', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_mode', models.TextField(null=True)),
                ('amount', models.FloatField(null=True)),
                ('payment_date_time', models.DateTimeField(null=True)),
                ('bank_ac_no', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=20, null=True)),
                ('description', models.TextField(null=True)),
                ('unit_of_measurement', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product_category',
            fields=[
                ('product_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_category_name', models.CharField(max_length=20, null=True)),
                ('product_category_image', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_product_category',
            fields=[
                ('sub_product_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_product_category_name', models.CharField(max_length=20, null=True)),
                ('sub_product_category_image', models.TextField(null=True)),
                ('product_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_side.product_category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('product_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('product_date', models.DateField(null=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_side.product')),
            ],
        ),
        migrations.CreateModel(
            name='Product_photos',
            fields=[
                ('product_photos_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_photo', models.TextField(null=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_side.product')),
            ],
        ),
        migrations.CreateModel(
            name='Product_history',
            fields=[
                ('product_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('date', models.DateField(null=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_side.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='sub_product_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_side.sub_product_category'),
        ),
        migrations.AddField(
            model_name='product',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_side.user'),
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('price', models.FloatField(null=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_side.order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_side.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_side.payment'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_side.user'),
        ),
        migrations.CreateModel(
            name='EAuctionUserDetail',
            fields=[
                ('e_auction_user_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('bidPrice', models.FloatField(null=True)),
                ('maxRounds', models.IntegerField(null=True)),
                ('bidDateTime', models.DateTimeField(null=True)),
                ('e_auction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_side.eauction')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_side.user')),
            ],
        ),
        migrations.AddField(
            model_name='eauction',
            name='payment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_side.payment'),
        ),
        migrations.AddField(
            model_name='eauction',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_side.product'),
        ),
    ]
