# Generated by Django 4.2.9 on 2024-02-09 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0003_eauction_order_payment_product_product_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='delivery',
            fields=[
                ('delivery_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.TextField(null=True)),
                ('shop_no', models.IntegerField(null=True)),
                ('shop_name', models.CharField(max_length=20, null=True)),
                ('street_name', models.CharField(max_length=30, null=True)),
                ('delivery_status', models.CharField(max_length=45, null=True)),
                ('status_date_time', models.DateTimeField(null=True)),
                ('estimated_delivery', models.DateTimeField(null=True)),
                ('delivery_charges', models.FloatField(null=True)),
                ('isDelivered', models.BooleanField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='product_history',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='sub_product_category',
            name='product_category_id',
        ),
        migrations.AlterModelOptions(
            name='eauctionuserdetail',
            options={'managed': False},
        ),
        migrations.RenameField(
            model_name='eauction',
            old_name='final_price',
            new_name='opening_price',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='bank_ac_no',
            new_name='transaction_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='business_description',
        ),
        migrations.RemoveField(
            model_name='area',
            name='city_id',
        ),
        migrations.RemoveField(
            model_name='eauction',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='eauction',
            name='total_rounds',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_mode',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sub_product_category_id',
        ),
        migrations.AddField(
            model_name='eauction',
            name='e_auction_cancel',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='eauction',
            name='e_auction_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='eauction',
            name='isCompleted',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='e_auction_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_side.eauction'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_side.product_category'),
        ),
        migrations.AddField(
            model_name='user',
            name='business_name',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='establishment_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='language_preference',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='licence_image',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='licence_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='shop_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='shop_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='street_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='weekly_off',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='area_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=28, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user_type',
            name='user_type_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterModelTable(
            name='eauction',
            table='EAuction',
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderDetail',
        ),
        migrations.DeleteModel(
            name='Product_history',
        ),
        migrations.DeleteModel(
            name='ProductDetail',
        ),
        migrations.DeleteModel(
            name='Sub_product_category',
        ),
        migrations.AddField(
            model_name='delivery',
            name='eAuction_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_side.eauction'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='pincode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_side.area'),
        ),
    ]
