# Generated by Django 4.2.9 on 2024-02-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0004_delivery_remove_order_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gst_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterModelTable(
            name='eauctionuserdetail',
            table='EAuctionUserDetail',
        ),
    ]
