# Generated by Django 4.2.9 on 2024-02-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0005_user_gst_no_alter_eauctionuserdetail_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_category',
            name='product_category_image',
            field=models.ImageField(null=True, upload_to='pc_images/'),
        ),
    ]
