# Generated by Django 4.2.9 on 2024-03-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0006_alter_product_category_product_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='estimated_delivery',
            new_name='estimated_delivery_date_time',
        ),
        migrations.RenameField(
            model_name='eauction',
            old_name='e_auction_date_time',
            new_name='e_auction_end_date_time',
        ),
        migrations.RemoveField(
            model_name='eauction',
            name='e_auction_duration',
        ),
        migrations.AddField(
            model_name='delivery',
            name='is_delivery_charges_paid',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='eauction',
            name='e_auction_start_date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='pincode',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
