# Generated by Django 4.2.9 on 2024-03-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0007_rename_estimated_delivery_delivery_estimated_delivery_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='licence_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
