# Generated by Django 4.2.9 on 2024-03-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0008_alter_user_licence_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='is_delivery_charges_paid',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='display_picture',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
