# Generated by Django 4.2.9 on 2024-03-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0009_alter_delivery_is_delivery_charges_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='isDelivered',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='eauction',
            name='e_auction_cancel',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='eauction',
            name='isCompleted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
